name: Typedocs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
        
    - name: Install Typedoc
      run: npm install typedoc
      env:
        CI: true
        
    - name: Build Docs
      run: npm run docs
      env:
        CI: true

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: docs # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
